name: Build Java + Vue Project

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build on windows
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, 'windows')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package application with jpackage
        shell: cmd
        run: >
          jpackage
          --input dist
          --main-jar tg-ff-inner.bundle
          --main-class ff.Agent
          --name tg-ff-inner
          --type app-image
          --jlink-options "--no-man-pages" 
          --jlink-options "--no-header-files" 
          --icon icons\\win.ico

      - name: Zip the packaged application
        shell: cmd
        run: powershell Compress-Archive -Path tg-ff-inner -DestinationPath tg-ff-inner-windows-x64.zip

      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: tg-ff-inner-windows-x64
          path: tg-ff-inner-windows-x64.zip
